# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25, unique=True)),
                ('player', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
