# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='player',
            new_name='captain',
        ),
    ]
