# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20171121_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='c4_players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='captain',
            new_name='player',
        ),
    ]
