# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20171123_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='../static/media/', verbose_name='Изображение')),
            ],
        ),
        migrations.DeleteModel(
            name='c4_players',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
