# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20171123_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='../../learnforkatedjango/media/', verbose_name='Изображение'),
        ),
    ]
