# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20171124_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='../../learnforkatedjango/media/images/news/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='../../learnforkatedjango/media/images/news/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
