# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default='2017-11-25'),
        ),
    ]
