# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20171125_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default='2017-11-26'),
        ),
    ]
