# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20171126_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, help_text='200x200px', upload_to='static/media/images/news/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
