# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20171126_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, help_text='200x200px', upload_to='static/media/images/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
