# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20171126_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default='2017-12-01'),
        ),
    ]
