# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20171207_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default='2017-12-12'),
        ),
    ]
